export const Users = [
    {
      "id": 1,
      "job_name": "Software Engineer",
      "job_description": "html, css, javascript, nodejs, express, mongodb",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 2,
      "job_name": "Software Engineer",
      "job_description": "Java, Spring Boot, SQL, Angular",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 3,
      "job_name": "Junior Software Engineer",
      "job_description": "Java, Spring Boot, SQL, Angular",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 4,
      "job_name": "Junior Software Engineer",
      "job_description": "Java, Spring Boot, SQL, Angular",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 5,
      "job_name": "Junior Software Engineer",
      "job_description": "Python, Django, SQL",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 6,
      "job_name": "Software Engineer",
      "job_description": "Java, Spring Boot, SQL, Angular with +2yr exprience",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 7,
      "job_name": "Junior Software Engineer",
      "job_description": "Java, Spring Boot, SQL, Angular +3yr exprience",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 8,
      "job_name": "Junior Application Developer",
      "job_description": "Java, XML, SQL, Firebae",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 9,
      "job_name": "Junior Application Developer",
      "job_description": "Java, SQL, Angular, Dart, React Native",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 10,
      "job_name": "Data Engineer",
      "job_description": "AWS, C++, Python, Apache Hadoop +3yr exprince",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 11,
      "job_name": "Data Engineer",
      "job_description": "AWS, C++, Python, Apache Hadoop +5yr exprince",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 12,
      "job_name": "Junior Data Engineer",
      "job_description": "AWS, C++, Python, Apache Hadoop",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 13,
      "job_name": "Graphic Designing",
      "job_description": "Adobe Photoshop, Sketch, Adobe Illustrator,Lunacy",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 14,
      "job_name": "Junior Graphic Designing",
      "job_description": "Adobe Photoshop, Sketch, Adobe Illustrator,Lunacy",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 15,
      "job_name": "FrontEnd Engineer",
      "job_description": "HTML,CSS,Javascript,ReactJs,JSX,Redux",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 16,
      "job_name": "Junior FrontEnd Engineer",
      "job_description": "HTML,CSS,Javascript,ReactJs,JSX,Redux",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 17,
      "job_name": "FrontEnd Engineer",
      "job_description": "HTML,CSS,Javascript,ReactJs,JSX,Redux",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 18,
      "job_name": "BackEnd Engineer",
      "job_description": "NodeJs,ExpressJs,MongoDB,SQL",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 19,
      "job_name": "BackEnd Engineer",
      "job_description": "NodeJs,ExpressJs,MongoDB,SQL",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
    {
      "id": 20,
      "job_name": "Junior BackEnd Engineer",
      "job_description": "NodeJs,ExpressJs,MongoDB,SQL,Java",
      "email": "emcclune0@xrea.com",
      "gender": "Female",
    },
]